{
 "title": "ML Service Monitoring (App + Infra + Model)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Model | Prediction Distribution (Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(prediction_value_histogram_bucket{le!=\"+Inf\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Application | Error Rate (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    { "expr": "prediction_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application | RPS (Requests per Minite) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(prediction_requests_total[1m])) * 60",
     "legendFormat": "{{total}}"
    }
   ]
  },
  {
   "title": "Infrastructure | CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Infrastructure | RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{rss}}" }
   ]
  }
 ]
}